In [2]:
import numpy as np
import time

N=10_00_000

python_list = list(range(N))

start=time.time()
total=sum(python_list)
python_time=time.time()-start

print(f'Python List: {python_time:.4f} seconds')


Python List: 0.0063 seconds


In [3]:
#Time Calculation
import numpy as np

numpy_array = np.arange(N)
start = time.time()
total = numpy_array.sum()
numpy_time = time.time() - start

print(f'NumPy array:  {numpy_time:.4f} seconds')
print(f'NumPy is {python_time / numpy_time:.0f}x faster')


NumPy array:  0.0051 seconds
NumPy is 1x faster


In [4]:
numpy_array = np.arange(N)
print(numpy_array)
np.array

[     0      1      2 ... 999997 999998 999999]


<function numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)>

In [5]:
# From existing Python data
# From a list
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# From a nested list
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
#Zeros and ones : used for initialising weights and biases
# np.zeros : a matrix of all zeros
# Used to initialise: bias vectors, output buffers
zeros = np.zeros((3, 4))    # 3 rows, 4 columns
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# np.ones : used to initialise gates, masks
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# np.full : fill with any value
mask = np.full((3, 3), fill_value=-1e9)  # used in attention masking
print(mask)

[[-1.e+09 -1.e+09 -1.e+09]
 [-1.e+09 -1.e+09 -1.e+09]
 [-1.e+09 -1.e+09 -1.e+09]]


In [10]:
#Ranges and generating sequences
# np.arange(start, stop, step) : like Python range() but returns ndarray
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


In [11]:
## np.linspace(start, stop, num) : evenly spaced, INCLUDES endpoint
# Used constantly for: learning rate schedules, plotting axes, sin/cos curves
x = np.linspace(0, 1, 5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
#Random arrays : the heart of ML initialisation
# Always set a seed for reproducibility in experiments
rng = np.random.default_rng(42)

weights = rng.normal(
    0, 0.01, (4,3)
)

print(weights)


[[ 0.00304717 -0.01039984  0.00750451]
 [ 0.00940565 -0.01951035 -0.0130218 ]
 [ 0.0012784  -0.00316243 -0.00016801]
 [-0.00853044  0.00879398  0.00777792]]


In [13]:
#Before doing anything with an array, check these:
img_batch = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(img_batch.shape)

print(img_batch.ndim)    # (dimensional array)

print(img_batch.dtype)

print(img_batch.size)    # Total elements

print(img_batch.nbytes)  # size * bytes per element

(3, 3)
2
int64
9
72


In [15]:
marks = np.array([70,80,90])
print(marks)
marks =marks + 5
print(marks)

[70 80 90]
[75 85 95]


In [16]:
students = 100

attendance = np.random.randint(
    50,
    100,
    students
)

marks = np.random.randint(
    30,
    100,
    students
)

projects = np.random.randint(
    1,
    10,
    students
)

communication = np.random.randint(
    1,
    10,
    students
)

dataset = np.column_stack(
    (
        attendance,
        marks,
        projects,
        communication
    )
)

print(dataset)

[[78 44  3  3]
 [99 83  2  2]
 [76 96  2  5]
 [89 62  2  9]
 [75 95  6  1]
 [92 94  6  1]
 [85 36  9  8]
 [60 52  8  6]
 [65 66  4  1]
 [71 61  3  7]
 [90 85  3  1]
 [84 43  6  1]
 [72 50  8  1]
 [63 59  9  4]
 [59 45  6  4]
 [74 48  4  9]
 [57 92  5  6]
 [68 31  7  8]
 [81 63  5  5]
 [68 92  7  4]
 [99 68  5  1]
 [82 49  8  7]
 [96 76  9  3]
 [83 30  4  1]
 [93 42  5  6]
 [97 96  2  6]
 [68 74  5  6]
 [61 76  1  7]
 [87 80  3  5]
 [88 54  6  3]
 [98 68  8  1]
 [93 65  3  5]
 [62 42  7  9]
 [69 56  6  1]
 [64 33  2  1]
 [83 55  3  5]
 [99 62  5  6]
 [55 96  4  7]
 [85 46  9  9]
 [65 96  1  2]
 [55 67  3  8]
 [61 57  1  9]
 [98 65  3  9]
 [84 61  7  6]
 [93 47  8  2]
 [73 76  9  9]
 [94 80  4  6]
 [87 68  3  5]
 [95 61  5  4]
 [81 60  5  7]
 [86 69  1  7]
 [97 50  4  2]
 [53 48  5  4]
 [57 48  6  1]
 [86 88  6  3]
 [55 53  7  8]
 [60 55  1  4]
 [78 32  2  3]
 [58 95  2  5]
 [91 33  6  1]
 [72 82  3  5]
 [58 57  5  8]
 [65 38  3  7]
 [69 33  5  1]
 [51 64  9  6]
 [98 86  4  4]
 [88 43  4

In [17]:
score = (
    attendance
    + marks
    + projects*10
    + communication*10
)

top_students = score > 180

print(top_students.sum())

91


In [18]:
movies = np.array([
"Interstellar",
"Inception",
"Avatar",
"Titanic",
"Oppenheimer"
])

In [20]:
print(movies[2])
print(movies[0])
print(movies[0:3])

Avatar
Interstellar
['Interstellar' 'Inception' 'Avatar']


In [22]:
ratings = np.array([
[5,4,3],
[3,5,4],
[4,2,5]
])

print(ratings[:,1])
print(ratings[1,:])
print(ratings[0,1])

[4 5 2]
[3 5 4]
4


In [23]:
scores = np.array([90, 45, 78, 35, 92, 88])
scores=scores[scores > 80]
print(scores)

[90 92 88]


In [24]:
tokens = np.array([
101,
2054,
2003,
102,
0,
0,
0
])

tokens=tokens[tokens!=0]
print(tokens)

[ 101 2054 2003  102]
